### ISSUE TITLE
Espaço para observação

### ISSUE THREAD

**Issue by napolianasl** [tarley/envelheser#10]
Cliente pediu na sprint passada um campo para colocar observação relacionadas as perguntas fechadas, e foi acordado com o cliente para essa entrega.

![image](https://cloud.githubusercontent.com/assets/18200760/15225481/04cc8932-1855-11e6-941f-0e4e896fa9f3.png)

**Comment by CarlosHenriqueFerreiraGomes** [comment]
Esta regra de negócio foi inclusa depois que a sprint havia terminado. Favor aguardar nova versão.

**Comment by napolianasl** [comment]
Foi acordado com o cliente na ultima Sprint, que seria entregue nessa Sprint. obrigada

**Comment by CarlosHenriqueFerreiraGomes** [comment]
Ainda não subiu a versão final. Favor aguardar.

**Comment by andrescarvalho** [comment]
Boa noite, Carlos!
Favor descrever qual a solução tomada para este item caso tenha sido resolvido. 
Se a decisão tomada foi resolver o item na sprint final, por favor manter o bug aberto e fechá-lo após ser resolvido.

**Comment by CarlosHenriqueFerreiraGomes** [comment]
André,

Conforme conversado, esta solução já foi resolvida.
