### ISSUE TITLE
Habitos e vícios

### ISSUE THREAD

**Issue by napolianasl** [tarley/envelheser#18]
a pergunta outros hábitos e vícios devem estar no final  depois das drogas ilícitas

**Comment by RodrigoRoliveira** [comment]
Ordem da pergunta foi alterada para que "outros hábitos e vícios" fique por ultima

**Comment by CarlosHenriqueFerreiraGomes** [comment]
Não há subgrupo para esta pergunta, por isso não tem como colocá-lo no final do grupo pai "Hábitos e vícios". Gentileza verificar com o usuário um nome de subgrupo para para que a alteração possa ser feita.
