### ISSUE TITLE
 necessidade PsicoEspirituais

### ISSUE THREAD

**Issue by napolianasl** [tarley/envelheser#19]
está: mormo e testemunha de jeová,
 não deve mais conter o mormo e testemunha.
Deve conter espirita

![fig 1](https://cloud.githubusercontent.com/assets/18200760/15233923/eb0b1396-1882-11e6-8bf4-5a987fa02c9b.png)
![fig2](https://cloud.githubusercontent.com/assets/18200760/15233955/1ff0c5a6-1883-11e6-92ff-6d4d5fdc4c5e.png)

**Comment by RodrigoRoliveira** [comment]
haverá possibilidade de um paciente ser "mormo e testemunha de jeová", por isso não será retirada. Religião espirita incluída.
