### ISSUE TITLE
Alteração na visualização na tela 100% do Site

### ISSUE THREAD

**Issue by Johnnyx01** [tarley/envelheser#2]
Verificar o motivo da quebra das resposta Sim/Não em diferentes navegadores com o zoom 100%

![visual-firefox](https://cloud.githubusercontent.com/assets/18200757/14905097/07c25936-0d84-11e6-91b6-839fc2d6f2c8.png)
Visualização no Firefox
![visual-explorer](https://cloud.githubusercontent.com/assets/18200757/14905096/07c174ee-0d84-11e6-8914-94b6c72c5ca9.png)
Visualização no Explorer

Obs: Quando diminui o tamanho do zoom no Firefox ele fica normal, como no Explorer quando aumenta fica um em cima do outro igual no Firefox

**Comment by danieldcaldeira** [comment]
Johnny, testei aqui em vários navegadores e com zoom a 100% esta normal.  Quando o zoom é elevado a mais de 110% ai sim acontece, mas isso não é uma quebra na verdade o layout do site é responsivo logo ele reajusta os componentes para que caibam na tela sem precisar da barra de rolagem horizontal.
