### ISSUE TITLE
Eliminação intestinal

### ISSUE THREAD

**Issue by napolianasl** [tarley/envelheser#20]
esta: déficit prévio no auto.... / constipação
não deve conter essas palavras
![fig4](https://cloud.githubusercontent.com/assets/18200760/15234166/3175713a-1885-11e6-8291-f95bd94da73d.png)

![fig3](https://cloud.githubusercontent.com/assets/18200760/15234127/b7c256fa-1884-11e6-8cd9-6797b23d8a26.png)

**Comment by RodrigoRoliveira** [comment]
conforme alinhado, não será retirado perguntas ate apresentação para o cliente.

**Comment by RodrigoRoliveira** [comment]
Alterado conforme pedido.
