### ISSUE TITLE
Desmarcação das respostas das perguntas do tipo radio no formulário

### ISSUE THREAD

**Issue by katernets** [tarley/envelheser#21]
O sistema não está aceitando mais de uma marcação de reposta das perguntas do tipo radio no formulário. Realizando a marcação de uma resposta a próxima pergunta respondida automaticamente desmarca a resposta anterior da pergunta. Segue print.  
- 

Pergunta Fácies do grupo Exame Físico e perguntas do grupo Coong.

![coong](https://cloud.githubusercontent.com/assets/18200769/15277542/35ebe45a-1ade-11e6-8cfe-d92f39c5c4a3.png)

**Comment by CarlosHenriqueGitHub** [comment]
Ater, bom dia

O tipo de resposta rádio tem esta propriedade, marcar um e somente um item para a pergunta.
Se desejar marcar mais de uma resposta, deverá alterar o tipo de pergunta para Checkbox. 
Veremos com os usuários no dia 19/05, qual seria o mais adequado.
