### ISSUE TITLE
Quebra de Linha

### ISSUE THREAD

**Issue by Johnnyx01** [tarley/envelheser#24]
Quebra de linha na formatação das respostas.
Não estão alinhadas, uma forma melhor de definir em uma possível linha para que o cliente não se perca em qual resposta, ou sombreamento.

E a definição da marcação do lado esquerdo.

![bug quebra de linha](https://cloud.githubusercontent.com/assets/18200757/15411791/d7feaa6c-1df8-11e6-8c23-cf4da2f3b1de.PNG)

**Comment by Sartori401** [comment]
Falha já solucionada
