### ISSUE TITLE
Paciente não apresenta RG

### ISSUE THREAD

**Issue by VitorAless** [tarley/envelheser#27]
Ao realizar a busca de um paciente o dado RG aparece mas ao acessar os dados cadastrais o campo RG aparece em branco.
![img01](https://cloud.githubusercontent.com/assets/18728754/15763967/ab2bb290-28fd-11e6-80d3-1728d14cad23.png)
![img02](https://cloud.githubusercontent.com/assets/18728754/15763968/ae9cdf08-28fd-11e6-9117-c0a4074c901a.png)

**Comment by CarinaRoriz** [comment]
Resolvido
