### ISSUE TITLE
Preenchimento de campo relacionado

### ISSUE THREAD

**Issue by VitorAless** [tarley/envelheser#3]
mesmo com a opção não marcada foi permitido escrever no campo relacionado e salvar o prontuário.O paciente utilizado neste teste foi Vitor Alessandro sendo que o teste foi realizado em: http://envelheser.com/cadastro.php? segundo o caso de teste TC020.
![img01](https://cloud.githubusercontent.com/assets/18728754/14906552/d68a13b8-0d92-11e6-836c-515b75239d79.png)

**Comment by CarinaRoriz** [comment]
Vitor, acordamos que o preenchimento desses campos seriam livres mesmo com a opção "Não" selecionada, para a inclusão de observações.

**Comment by jcheringer** [comment]
Conforme esclarecido pela Carina, o preenchimento dos campos é livre mesmo que seja selecionada a opção não.
