### ISSUE TITLE
Erro na tela, Alergia? Qual? (seria o certo)

### ISSUE THREAD

**Issue by napolianasl** [tarley/envelheser#9]
![image](https://cloud.githubusercontent.com/assets/18200760/15224738/6d5c7baa-1851-11e6-862f-85d63c72b0ee.png)

**Comment by CarlosHenriqueFerreiraGomes** [comment]
Esta regra de negócio foi inclusa depois que a sprint havia terminado. Favor aguardar nova versão.

**Comment by napolianasl** [comment]
o "qual" está desde a planilha velha. favor conferir, obrigada

**Comment by CarlosHenriqueFerreiraGomes** [comment]
Alterado.
